### PR TITLE
Remove FilteredPoolFetcher

### PR DESCRIPTION
**Pull request by vkgnosis**
The main component (PriceEstimator) using the pool fetcher already
checks for deny listed tokens so there is no need for it anymore.

The other use is for fetching uniswap liquidity in the driver in
solver/src/liquidity/uniswap.rs:82 which is fine too as we only consider
base_tokens as path candidates and the original orders have already been
filtered by the order book.

This came up in #618  . I think the historical reason for the filtered pool fetcher is that it used to be the only place where we filtered unsupported tokens and eventually we introduced the filtering directly into price estimator and fee calculation.

### Test Plan
adapted test

### CODE REVIEW

**Review by fleupold — APPROVED** [review]
<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia2.giphy.com%2Fmedia%2FxT0GqimU9dTwmE5lra%2Fgiphy.gif&token=red" data-gitmeme-token="red"></a>

**Review by nlordell — APPROVED** [review]
Awesome.

**Review by bh2smith — APPROVED** [review]
Looks and sounds great. I only wonder if we have to worry about the possibility of old orders which are not yet expired containing unsupported tokens.

**Comment by vkgnosis** [comment]
get solvable orders filters our unsupported tokens so should be fine

**Pull request merged**
