### PR TITLE
Update 1Inch API to v4.1

### LINKED ISSUE #1560: Update API endpoints of OneInchClientImpl to v4.1
`OneInchClientImpl` mostly relies on the older v3.0 API. This is a bit worrying because the endpoints seem to be no longer documented anywhere.
Most of the endpoints we currently also exist under the `v4.1` API. Some endpoints now support different parameters, though.
It seems like the functionality of `/v3.0/protocols` can now be found under `/v4.1/1/liquidity-sources`.
Since the endpoints didn't change too much updating them shouldn't be too much work.

### PR DESCRIPTION
**Pull request by MartinquaXD**
Fixes #1560

We have been using 1Inch API v3.0 for quite a while. There isn't even any documentation online available anymore.
Upgrading to v4.1 makes it easier to reason about changes in the future and also offers some new parameters to configure quotes and swaps.
Note that I'm not able to find any documentation about v4.1 specifically but I got confirmation from the 1Inch team that v4.0 and v4.1 are equivalent except that v4.1 is using EIP-1559 gas prices instead of the old gas prices.

The /swap endpoint got some new parameters and /protocols became /liquidity-sources.

### Test Plan
Update existing tests
Added new test parsing the response from /liquidity-sources
Manual test run with:
```
cargo run -p solver -- \                        INT ✘  7m 46s    15:12:36 
  --solver-account 0xa6DDBD0dE6B310819b49f680F65871beE85f517e \
  --baseline-sources UniswapV2,SushiSwap \
  --node-url <NODE_URL> \
  --transaction-strategy DryRun \
  --solvers OneInch,Baseline \
  --orderbook-url https://protocol-mainnet.gnosis.io/api/
```

### Release notes
Use 1Inch API v4.1 instead of v3.0

### CODE REVIEW

**Comment by nlordell** [comment]
Just a question, is this the same as the commit that was reverted because of parsing issues in the solver?

**Comment by MartinquaXD** [comment]
#1578 caused parsing errors with `/swap` which needed to be fixed. This in itself was trivial but right after fixing the issue many settlements failed during my local test. Because I assumed the reason was not so easy to find, I reverted #1578 to not break `main`.
After some investigation it seems like not the new API code was responsible for simulation failures but high volatility caused the settlement to no longer respect the slippage requirements.
Because this PR is quite big and most of it has already been reviewed I quickly note what changed compared to the old PR:
```diff
git diff 223ddf3851bb244ed9cf3164f4bcb5a814b95d2d

diff --git a/crates/shared/src/oneinch_api.rs b/crates/shared/src/oneinch_api.rs
index 525a185..083c828 100644
--- a/crates/shared/src/oneinch_api.rs
+++ b/crates/shared/src/oneinch_api.rs
@@ -366,8 +366,9 @@ pub struct Transaction {
     #[serde(with = "u256_decimal")]
     pub value: U256,
     #[serde(with = "u256_decimal")]
-    pub gas_price: U256,
-    pub gas: u64,
+    pub max_fee_per_gas: U256,
+    #[serde(with = "u256_decimal")]
+    pub max_priority_fee_per_gas: U256,
 }

 impl std::fmt::Debug for Transaction {
@@ -377,8 +378,8 @@ impl std::fmt::Debug for Transaction {
             .field("to", &self.to)
             .field("data", &format_args!("0x{}", hex::encode(&self.data)))
             .field("value", &self.value)
-            .field("gas_price", &self.gas_price)
-            .field("gas", &self.gas)
+            .field("max_priority_fee_per_gas", &self.max_priority_fee_per_gas)
+            .field("max_fee_per_gas", &self.max_fee_per_gas)
             .finish()
     }
 }
@@ -716,8 +717,8 @@ mod tests {
                 "to": "0x11111112542d85b3ef69ae05771c2dccff4faa26",
                 "data": "0x2e95b6c800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000de0b6b3a764000000000000000000000000000000000000000000000000001b1038e63128bd548d0000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000180000000000000003b6d034026aad2da94c59524ac0d93f6d6cbf9071d7086f2",
                 "value": "1000000000000000000",
-                "gasPrice": "154110000000",
-                "gas": 143297
+                "maxFeePerGas": "123865303708",
+                "maxPriorityFeePerGas": "2000000000"
               }
             }"#,
         )
@@ -762,8 +763,8 @@ mod tests {
                     )
                     .unwrap(),
                     value: 1_000_000_000_000_000_000u128.into(),
-                    gas_price: 154_110_000_000u128.into(),
-                    gas: 143297,
+                    max_fee_per_gas: 123_865_303_708u128.into(),
+                    max_priority_fee_per_gas: 2_000_000_000u128.into()
                 },
             })
         );

```

**Review by nlordell — APPROVED** [review]

**Comment by nlordell** [comment]
I see that we no longer have the `gas` field:
```
-    pub gas: u64,
```

Is this included maybe as `gasLimit` now?

**Review by nlordell — APPROVED** [review]
`gas` is back!

**Comment by MartinquaXD** [comment]
Brought back the gas and updated the diff ☝️

**Comment by MartinquaXD** [comment]
Further testing revealed that parsing errors can still happen but very rarely.
The following `/swap` response can not be parsed because the `tx.data` is of odd length and `hex::decode()` (which we use for decoding) requires even length.
Can we fix this by padding the value ourselves? And if so, how would we have to pad it?
```json
{
    "fromToken": {
        "symbol": "USDT",
        "name": "Tether USD",
        "address": "0xdac17f958d2ee523a2206206994597c13d831ec7",
        "decimals": 6,
        "logoURI": "https: //tokens.1inch.io/0xdac17f958d2ee523a2206206994597c13d831ec7.png"
    },
    "toToken": {
        "symbol": "DAI",
        "name": "Dai Stablecoin",
        "decimals": 18,
        "address": "0x6b175474e89094c44da98b954eedeac495271d0f",
        "logoURI": "https: //tokens.1inch.io/0x6b175474e89094c44da98b954eedeac495271d0f.png",
        "eip2612": true
    },
    "toTokenAmount": "14247143871029617771673",
    "fromTokenAmount": "14260000000",
    "protocols": [
        [
            [
                {
                    "name": "UNISWAP_V3",
                    "part": 100,
                    "fromTokenAddress": "0xdac17f958d2ee523a2206206994597c13d831ec7",
                    "toTokenAddress": "0x6b175474e89094c44da98b954eedeac495271d0f"
                }
            ]
        ]
    ],
    "tx": {
        "from": "0x9008d19f58aabd9ed0d60971565aa8510560ab41",
        "to": "0x1111111254fb6c44bac0bed2854e76f90643097d",
        "data": "0xe449022e0000000000000000000000000000000000000000000000000000000351f65500000000000000000000000000000000000000000000000303911ee43b6377a02d00000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000018000000000000000000000006f48eca74b38d2936b02ab603ff4e36a6c0e3a77cfee7c08",
        "value": "0",
        "gas": 0,
        "maxFeePerGas": "145277100617",
        "maxPriorityFeePerGas": "2000000000"
    }
}
```

**Comment by MartinquaXD** [comment]
The error didn't reappear while running the solver locally for 2 more hours. I'm willing to let this one slide and merge anyway.

**Comment by nlordell** [comment]
> response can not be parsed because the `tx.data` is of odd length [...] I'm willing to let this one slide and merge anyway.

To me this sounds like a bug on the 1Inch side of things (maybe something that we can share with them?). I also am willing to let this slide and merge anyways.

> Can we fix this by padding the value ourselves?

Not a fan of this - do we pad with a leading 0 or trailing 0?

Let's reach out to the 1Inch team to see if this is expected and whether or not this is something that should be fixed on their end.

**Pull request merged**
