### PR TITLE
Use global prometheus registry

### PR DESCRIPTION
**Pull request by taminomara**
This is the first step towards metrics refactoring discussed in [this proposal][1].

[1]: https://gnosisinc.slack.com/archives/C022S0FM1GW/p1626721489006400

### CODE REVIEW

**Review by vkgnosis — APPROVED** [review]

**Comment by taminomara** [comment]
I've realised that both solver and orderbook metrics live in the same namespace. We can't use the default registry with this setup because we need to configure common prefix for metric names.

**Comment by taminomara** [comment]
Ok I'll use the same branch to implement this, reopening.

**Review by nlordell — APPROVED** [review]

**Comment by vkgnosis** [comment]
> I've realised that both solver and orderbook metrics live in the same namespace. We can't use the default registry with this setup because we need to configure common prefix for metric names.

Ah, we do for the e2e test and I would like that to continue to work. I guess there can be a global lazily initialized function orderbook_metrics and solver_metrics.

**Comment by taminomara** [comment]
> Ah, we do for the e2e test and I would like that to continue to work. I guess there can be a global lazily initialized function orderbook_metrics and solver_metrics that return the respective registry.

This wouldn't work with common components. For example, transport just gets a global registry and reports its metrics. How would transport know if it should use `orderbook_metrics` or `solver_metrics`?

I'm not sure how to fix this issue. To be completely honest, I'm not sure it needs fixing. I think e2e should just spawn multiple processes, one per service. This way we're as close to the actual setup as possible, and we actually test `main` functions as well.

**Comment by vkgnosis** [comment]
I think you are right that it doesn't need fixing. If you create multiple transports then it makes sense that they use the same registry. And transport metrics do not need a separate orderbook or solver prefix because we can still distinguish them on a per pod basis.

**Review by fleupold — COMMENTED** [review]
I really like the idea of splitting the Registry and Metrics and having each subcomponent implements its own metrics (having the large metrics component implementing all these traits is painful as you said).

I'm not convinced that using global state for the registry/metrics is really necessary. I think passing a registry as part of the constructor is not so bad and would avoid setting precedence for creating and using non trivial global state in our codebase.

Just a thought, not blocking this if you think that using a global registry is fine.

**Pull request merged**
