### PR TITLE
Use native token for http solver price estimates

### PR DESCRIPTION
**Pull request by vkgnosis**
This makes the prices more consistent and understandable.

### Test Plan
small enough change to not warrant

### CODE REVIEW

**Review by marcovc — APPROVED** [review]
Thanks. Still doesn't explain the bogus exchange rates, right?

**Comment by vkgnosis** [comment]
Not it doesn't.

**Review by bh2smith — APPROVED** [review]
Interesting. What was token0 before? Does this solve the issue @marcovc reported, or is this just something you noticed on the way.

**Comment by marcovc** [comment]
I've added token[0] before (It doesn't really matter which value the prices are denominated in, except for convenience).

**Pull request merged**
