### PR TITLE
Fetch aggregation pools in parallel

### PR DESCRIPTION
**Pull request by vkgnosis**
This speeds up PoolAggregator. I am still looking into other ways to speed up price estimation.

### Test Plan
short local test that  price estimates haven't changed

### CODE REVIEW

**Review by bh2smith — APPROVED** [review]
This is cool but does fetching the pools also fetch the reserves or it is only the static pool data?

**Comment by vkgnosis** [comment]
The PoolFetching trait fetches reserves. You can find this out by following the implementation in the code: https://github.com/gnosis/gp-v2-services/blob/9e4cd693a5d90c9d47601146f6dfd43912ab6aa7/shared/src/pool_fetching.rs#L246 .

**Comment by fleupold** [comment]
> This is cool but does fetching the pools also fetch the reserves or it is only the static pool data

@bh2smith What is static pool data in the context of a Uniswap pool?

**Review by fleupold — APPROVED** [review]
image

**Review by nlordell — APPROVED** [review]

**Comment by bh2smith** [comment]
> > This is cool but does fetching the pools also fetch the reserves or it is only the static pool data
> 
> 
> 
> @bh2smith What is static pool data in the context of a Uniswap pool?

Everything except the reserves.

**Pull request merged**
