### PR TITLE
Remove iteteration over AMM tokens

### LINKED ISSUE #892: [HTTP Solver] Gather price map from Limit Order Tokens
It was pointed it in https://github.com/gnosis/gp-v2-services/pull/890#discussion_r676572331 that we may not need to derive the keys of the price map from the amm's tokenset (espesially since balancer pools may include more than just token pairs), but rather construct this map from the Order set. This seems completely viable given that we don't even enforce uniform clearing prices for amm only tokens. 

Specifically, we should be able to derive executed tokens in the following snippet from `executed_limit_orders` rather than `executed_amms`:

https://github.com/gnosis/gp-v2-services/blob/8471398e4a4e779374fde95d0e98109f2bde5daf/solver/src/solver/http_solver/settlement.rs#L185-L220

### PR DESCRIPTION
**Pull request by bh2smith**
Fixes #892

Not sure yet if prices for irrelevant intermediary tokens are actually necessary to pass into a settlement, but e2e here should tell us.

### Test Plan
May need to create a new e2e test that involves an amm token which is not actually traded directly.

### CODE REVIEW

**Review by fleupold — APPROVED** [review]
Maybe @fedgiac can confirm but the smart contract should not require prices for intermediate hops (only for the order's buy and sell token to compute the exchange rate and calculate the transfer amounts). The transfer amounts for interactions should be part of the interaction calldata directly.

**Review by fedgiac — APPROVED** [review]
Confirmed, amm prices are not needed. In principle we can use different prices in AMMs than those we give in the price vector.
I suppose this PR partially fixes #779?

**Comment by bh2smith** [comment]
Thanks for confirmation @fedgiac - I would say that this change is actually sufficient enough to close #779 - since I would imagine the WETH price is needed when buying ETH anyway. Would you agree, or do you think we should still tackle the last remaining bit of the issue before closing it?

**Comment by fedgiac** [comment]
WETH price is not needed when buying ETH, since ETH price is specified by pricing the "token" `0xeee..eee`.

**Comment by bh2smith** [comment]
> WETH price is not needed when buying ETH, since ETH price is specified by pricing the "token" `0xeee..eee`.

Do you think that perhaps this solution will also not include the WETH price since it only involves the buy and sell token of the orders themselves? Or is this some sort of automagic conversion happening under the hood?

**Comment by fedgiac** [comment]
If I recall it correctly, we automatically convert all ETH orders to WETH orders and later add back the ETH token and unwrapping if needed. So I'd expect that while picking the buy token here you get WETH.

**Comment by bh2smith** [comment]
> So I'd expect that while picking the buy token here you get WETH.

In that case it might not be worth our efforts to determine if the price should be weth or eth given that we would have to fetch additional info from outside the scope of this method.

**Pull request merged**
