### PR TITLE
Enable 1Inch API on gnosis chain

### PR DESCRIPTION
**Pull request by MartinquaXD**
1Inch now also supports gnosis chain.
Let's tap into that liquidity by adding GC chain id 100 to the allow list.

### Test Plan
Manual orderbook test:
```
2022-01-31T10:14:50.899Z DEBUG request{id=9}: shared::oneinch_api: Query 1inch API for url https://api.1inch.exchange/v4.1/100/quote?fromTokenAddress=0xe91d153e0b41518a2ce8dd3d7944fa863463a97d&toTokenAddress=0x9c58bacc331c9aa871afd802db6379a98e80cedb&amount=1000000000000000000&protocols=GNOSIS_CURVE%2CGNOSIS_HONEYSWAP%2CGNOSIS_LEVINSWAP%2CGNOSIS_ONE_INCH_LIMIT_ORDER_V2%2CGNOSIS_SWAPR%2CGNOSIS_SUSHI%2CGNOSIS_SYMMETRIC%2CWXDAI%2CGNOSIS_ELK&gasLimit=750000&complexityLevel=2&mainRouteParts=3&parts=3
2022-01-31T10:14:51.013Z DEBUG request{id=9}: shared::oneinch_api: Response from 1inch API: Ok("{\"fromToken\":{\"name\":\"Wrapped XDAI\",\"address\":\"0xe91d153e0b41518a2ce8dd3d7944fa863463a97d\",\"symbol\":\"WXDAI\",\"decimals\":18,\"logoURI\":\"https://raw.githubusercontent.com/1Hive/default-token-list/master/src/assets/xdai/0xe91d153e0b41518a2ce8dd3d7944fa863463a97d/logo.png\"},\"toToken\":{\"name\":\"Gnosis from Ethereum\",\"address\":\"0x9c58bacc331c9aa871afd802db6379a98e80cedb\",\"symbol\":\"GNO\",\"decimals\":18,\"logoURI\":\"https://tokens.1inch.io/0x6810e776880c02933d47db1b9fc05908e5386b96.png\"},\"toTokenAmount\":\"3709346561049407\",\"fromTokenAmount\":\"1000000000000000000\",\"protocols\":[[[{\"name\":\"GNOSIS_SYMMETRIC\",\"part\":100,\"fromTokenAddress\":\"0xe91d153e0b41518a2ce8dd3d7944fa863463a97d\",\"toTokenAddress\":\"0x9c58bacc331c9aa871afd802db6379a98e80cedb\"}]]],\"estimatedGas\":376835}")
2022-01-31T10:14:51.048Z DEBUG request{id=9}: shared::price_estimation::competition: received price estimate estimator_name=OneInch query=Query { sell_token: 0xe91d153e0b41518a2ce8dd3d7944fa863463a97d, buy_token: 0x9c58bacc331c9aa871afd802db6379a98e80cedb, in_amount: 1000000000000000000, kind: Sell } estimate=Estimate { out_amount: 3709346561049407, gas: 483226 }
2022-01-31T10:14:51.049Z DEBUG request{id=9}: shared::price_estimation::competition: received price estimate estimator_name=Baseline query=Query { sell_token: 0xe91d153e0b41518a2ce8dd3d7944fa863463a97d, buy_token: 0x9c58bacc331c9aa871afd802db6379a98e80cedb, in_amount: 1000000000000000000, kind: Sell } estimate=Estimate { out_amount: 3696771991030560, gas: 220417 }
2022-01-31T10:14:51.049Z DEBUG request{id=9}: shared::price_estimation::competition: winning price estimate query=Query { sell_token: 0xe91d153e0b41518a2ce8dd3d7944fa863463a97d, buy_token: 0x9c58bacc331c9aa871afd802db6379a98e80cedb, in_amount: 1000000000000000000, kind: Sell } winning_estimate=EstimateData { kind: Sell, estimator_name: "OneInch", estimate: Estimate { out_amount: 3709346561049407, gas: 483226 }, sell_over_buy: Ratio { numer: 1000000000000000000, denom: 3709346561049407 } }
```

Manual solver test:
```
2022-01-31T10:37:27.646Z DEBUG solver::solver::oneinch_solver: querying 1Inch swap api with SwapQuery { from_address: 0x9008d19f58aabd9ed0d60971565aa8510560ab41, slippage: Slippage(0.1), disable_estimate: Some(true), dest_receiver: None, referrer_address: None, burn_chi: None, allow_partial_fill: Some(false), quote: SellOrderQuoteQuery { from_token_address: 0xe91d153e0b41518a2ce8dd3d7944fa863463a97d, to_token_address: 0x9c58bacc331c9aa871afd802db6379a98e80cedb, amount: 998793225147997252, complexity_level: Some(Amount(2)), protocols: Some(["GNOSIS_CURVE", "GNOSIS_HONEYSWAP", "GNOSIS_LEVINSWAP", "GNOSIS_ONE_INCH_LIMIT_ORDER_V2", "GNOSIS_SWAPR", "GNOSIS_SUSHI", "GNOSIS_SYMMETRIC", "WXDAI", "GNOSIS_ELK"]), gas_limit: Some(Amount(750000)), main_route_parts: Some(Amount(3)), parts: Some(Amount(3)), fee: None, gas_price: None, virtual_parts: None, connector_tokens: None } }
2022-01-31T10:37:27.647Z DEBUG shared::oneinch_api: Query 1inch API for url https://api.1inch.exchange/v4.1/100/swap?fromTokenAddress=0xe91d153e0b41518a2ce8dd3d7944fa863463a97d&toTokenAddress=0x9c58bacc331c9aa871afd802db6379a98e80cedb&amount=998793225147997252&fromAddress=0x9008d19f58aabd9ed0d60971565aa8510560ab41&slippage=0.1&protocols=GNOSIS_CURVE%2CGNOSIS_HONEYSWAP%2CGNOSIS_LEVINSWAP%2CGNOSIS_ONE_INCH_LIMIT_ORDER_V2%2CGNOSIS_SWAPR%2CGNOSIS_SUSHI%2CGNOSIS_SYMMETRIC%2CWXDAI%2CGNOSIS_ELK&disableEstimate=true&complexityLevel=2&gasLimit=750000&mainRouteParts=3&parts=3&allowPartialFill=false
2022-01-31T10:37:27.801Z DEBUG shared::oneinch_api: Response from 1inch API: Ok("{\"fromToken\":{\"name\":\"Wrapped XDAI\",\"address\":\"0xe91d153e0b41518a2ce8dd3d7944fa863463a97d\",\"symbol\":\"WXDAI\",\"decimals\":18,\"logoURI\":\"https://raw.githubusercontent.com/1Hive/default-token-list/master/src/assets/xdai/0xe91d153e0b41518a2ce8dd3d7944fa863463a97d/logo.png\"},\"toToken\":{\"name\":\"Gnosis from Ethereum\",\"address\":\"0x9c58bacc331c9aa871afd802db6379a98e80cedb\",\"symbol\":\"GNO\",\"decimals\":18,\"logoURI\":\"https://tokens.1inch.io/0x6810e776880c02933d47db1b9fc05908e5386b96.png\"},\"toTokenAmount\":\"3704870250468858\",\"fromTokenAmount\":\"998793225147997252\",\"protocols\":[[[{\"name\":\"GNOSIS_SYMMETRIC\",\"part\":100,\"fromTokenAddress\":\"0xe91d153e0b41518a2ce8dd3d7944fa863463a97d\",\"toTokenAddress\":\"0x9c58bacc331c9aa871afd802db6379a98e80cedb\"}]]],\"tx\":{\"from\":\"0x9008d19f58aabd9ed0d60971565aa8510560ab41\",\"to\":\"0x1111111254fb6c44bac0bed2854e76f90643097d\",\"data\":\"0x7c025200000000000000000000000000a31bb36c5164b165f9c36955ea4ccbab42b3b28e00000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000180000000000000000000000000e91d153e0b41518a2ce8dd3d7944fa863463a97d0000000000000000000000009c58bacc331c9aa871afd802db6379a98e80cedb000000000000000000000000a31bb36c5164b165f9c36955ea4ccbab42b3b28e0000000000000000000000009008d19f58aabd9ed0d60971565aa8510560ab410000000000000000000000000000000000000000000000000ddc6d257d035c44000000000000000000000000000000000000000000000000000d2630b7be2e1500000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006c000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000004608000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000384ad0e7b1a00000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000320000000000000000000000000e91d153e0b41518a2ce8dd3d7944fa863463a97d00000000000000000000000000000009000000000000000000000000000000090000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000001400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000064eb5625d9000000000000000000000000e91d153e0b41518a2ce8dd3d7944fa863463a97d00000000000000000000000053ed0c2c6bb944d9421528e1abd1e042b330696b00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000080000000000000000000000053ed0c2c6bb944d9421528e1abd1e042b330696b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000a48201aa3f000000000000000000000000e91d153e0b41518a2ce8dd3d7944fa863463a97d00000000000000000000000000000000000000000000000000000000000000010000000000000000000000009c58bacc331c9aa871afd802db6379a98e80cedb0000000000000000000000000000000000000000000000000000000000000001ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000028000000000000000000000000000000000000000000000000000000000000044800000000000000000000000000000000000000000000000000000000000002400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000018414284aab000000000000000000000000000000000000000000000000000000000000008080000000000000000000000000000000000000000000000000000000000000440000000000000000000000009c58bacc331c9aa871afd802db6379a98e80cedb00000000000000000000000000000001000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000064d1660f990000000000000000000000009c58bacc331c9aa871afd802db6379a98e80cedb0000000000000000000000001111111254fb6c44bac0bed2854e76f90643097d00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000cfee7c08\",\"value\":\"0\",\"gas\":0,\"maxFeePerGas\":\"4752000017\",\"maxPriorityFeePerGas\":\"4752000010\"}}")
2022-01-31T10:37:27.806Z DEBUG solver::driver: solver 1Inch found solution: Settlement { encoder: SettlementEncoder { tokens: [0x9c58bacc331c9aa871afd802db6379a98e80cedb, 0xe91d153e0b41518a2ce8dd3d7944fa863463a97d], clearing_prices: {0xe91d153e0b41518a2ce8dd3d7944fa863463a97d: 3704870250468858, 0x9c58bacc331c9aa871afd802db6379a98e80cedb: 998793225147997252}, trades: [Trade { order: Order { order_meta_data: OrderMetaData { creation_date: 2022-01-31T10:37:21.011181Z, owner: 0x1a015ad600829d8b288bf3c50b9f557a2c12e9ca, uid: 0xb93663e4c96522779b49f04d17a2990d844eea8da7429c6a16c31081f54862381a015ad600829d8b288bf3c50b9f557a2c12e9ca61f7c2e6, available_balance: Some(9000000000000000000), executed_buy_amount: 0, executed_sell_amount: 0, executed_sell_amount_before_fees: 0, executed_fee_amount: 0, invalidated: false, status: Open, settlement_contract: 0x9008d19f58aabd9ed0d60971565aa8510560ab41, full_fee_amount: 1098228997916316 }, order_creation: OrderCreation { sell_token: 0xe91d153e0b41518a2ce8dd3d7944fa863463a97d, buy_token: 0x9c58bacc331c9aa871afd802db6379a98e80cedb, receiver: Some(0x1a015ad600829d8b288bf3c50b9f557a2c12e9ca), sell_amount: 998793225147997252, buy_amount: 3658722288854403, valid_to: 1643627238, app_data: 0x487b02c558d729abaf3ecf17881a4181e5bc2446429a0995142297e897b6eb37, fee_amount: 1206774852002748, kind: Sell, partially_fillable: false, signature: Eip712(EcdsaSignature { r: 0x63a6ca5746dd61d08c397bb91613993b2cad549b60c6628d60dd512a2bb19eed, s: 0x4ac91f9d80ac24942b9d4de4d1d7619423b8a7511a46ea7c922aaedb2d10dcd1, v: 27 }), sell_token_balance: Erc20, buy_token_balance: Erc20 } }, sell_token_index: 1, buy_token_index: 0, executed_amount: 998793225147997252, scaled_fee_amount: 1098228997916316, is_liquidity_order: false }], execution_plan: [Approve { token: 0xe91d153e0b41518a2ce8dd3d7944fa863463a97d, spender: 0x1111111254fb6c44bac0bed2854e76f90643097d }, Swap { from_token: Token { address: 0xe91d153e0b41518a2ce8dd3d7944fa863463a97d }, to_token: Token { address: 0x9c58bacc331c9aa871afd802db6379a98e80cedb }, from_token_amount: 998793225147997252, to_token_amount: 3704870250468858, protocols: [[[ProtocolRouteSegment { name: "GNOSIS_SYMMETRIC", part: 100.0, from_token_address: 0xe91d153e0b41518a2ce8dd3d7944fa863463a97d, to_token_address: 0x9c58bacc331c9aa871afd802db6379a98e80cedb }]]], tx: Transaction { from: 0x9008d19f58aabd9ed0d60971565aa8510560ab41, to: 0x1111111254fb6c44bac0bed2854e76f90643097d, data: 0x7c025200000000000000000000000000a31bb36c5164b165f9c36955ea4ccbab42b3b28e00000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000180000000000000000000000000e91d153e0b41518a2ce8dd3d7944fa863463a97d0000000000000000000000009c58bacc331c9aa871afd802db6379a98e80cedb000000000000000000000000a31bb36c5164b165f9c36955ea4ccbab42b3b28e0000000000000000000000009008d19f58aabd9ed0d60971565aa8510560ab410000000000000000000000000000000000000000000000000ddc6d257d035c44000000000000000000000000000000000000000000000000000d2630b7be2e1500000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006c000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000004608000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000384ad0e7b1a00000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000320000000000000000000000000e91d153e0b41518a2ce8dd3d7944fa863463a97d00000000000000000000000000000009000000000000000000000000000000090000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000001400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000064eb5625d9000000000000000000000000e91d153e0b41518a2ce8dd3d7944fa863463a97d00000000000000000000000053ed0c2c6bb944d9421528e1abd1e042b330696b00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000080000000000000000000000053ed0c2c6bb944d9421528e1abd1e042b330696b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000a48201aa3f000000000000000000000000e91d153e0b41518a2ce8dd3d7944fa863463a97d00000000000000000000000000000000000000000000000000000000000000010000000000000000000000009c58bacc331c9aa871afd802db6379a98e80cedb0000000000000000000000000000000000000000000000000000000000000001ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000028000000000000000000000000000000000000000000000000000000000000044800000000000000000000000000000000000000000000000000000000000002400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000018414284aab000000000000000000000000000000000000000000000000000000000000008080000000000000000000000000000000000000000000000000000000000000440000000000000000000000009c58bacc331c9aa871afd802db6379a98e80cedb00000000000000000000000000000001000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000064d1660f990000000000000000000000009c58bacc331c9aa871afd802db6379a98e80cedb0000000000000000000000001111111254fb6c44bac0bed2854e76f90643097d00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000cfee7c08, value: 0, max_fee_per_gas: 4752000017, max_priority_fee_per_gas: 4752000010, gas: 0 } }], unwraps: [] } }
```

### Release notes
Enable 1Inch solver and price estimator on gnosis chain

### CODE REVIEW

**Review by vkgnosis — APPROVED** [review]

**Review by josojo — APPROVED** [review]
Looks good. 

But before you merge, please also check one more time that gnosis chain integration also works with the enterprise url.

**Review by sunce86 — APPROVED** [review]
Looks good. Have you considered putting the supported chains in configuration so we could disable it faster if needed?

**Comment by vkgnosis** [comment]
I think it should continue to be hardcoded. If we have problems with this we can already disable 1inch alltogether in the GnosisChain pod.

**Comment by MartinquaXD** [comment]
> But before you merge, please also check one more time that gnosis chain integration also works with the enterprise url.

Did that, looks good.

**Pull request merged**
