### PR TITLE
Configure minimum discounted fee

### PR DESCRIPTION
**Pull request by nlordell**
This PR adds a configuration option for setting a minimum discounted fee amount. We want this because we currently have a flat fee subsidy, and in times of low gas prices, it _can_ happen that we end up with a 0 or negative fee amount after applying this fee discount.

In order to avoid these situations (since free trading is nice for our users but causes a bunch of other problems - like wash trading for example), we add a new configuration option for a lower bound on how much the fee can be discounted.

One quirk about how this was implemented, the amount represents the minimum fee **before** any multiplicative subsidies are applied. The reason for doing this is that:
- It made the code much easier (we already had logic for this, just hard-coded at 0).
- It was unclear to me whether or not we wanted things like the global fee factor and specifically partner fee factors to allow the final subsidized fee to go lower than this (e.g. PMMs should be able to place orders below this minimum right?).

Since I'm not 100% sure about the semantics here, I started a discussion in Slack. Feel free to review the rest of the code in the meantime.

### Test Plan

Adapted unit test for fees being capped at 0 to use a minimum amount.

### CODE REVIEW

**Review by fleupold — APPROVED** [review]
Great!

**Review by MartinquaXD — APPROVED** [review]
The changes look good overall.
I'm just a little concerned that the fee parameters are of type `f64`. Isn't that usually frowned upon if you are dealing with money because of rounding errors?
But since this is already an established pattern I don't see a reason to delay this PR.

**Review by bh2smith — COMMENTED** [review]
This looks fine, but I was expecting to see a change in some of the formulas s discussed in the slack [here](https://gnosisinc.slack.com/archives/CC3C5SMB5/p1640271637140400) that relates the min discounted fee with the other calculated fees like `fee = max(minFee,calculatedFee)` to ensure we always use the lower bound. Perhaps I have misunderstood the conversation. Or is this planned for a follow up PR?

**Review by josojo — APPROVED** [review]

**Comment by fleupold** [comment]
I'm going to merge this branch since it's accepted without any comments and this feature shouldn't wait another week.

**Comment by MartinquaXD** [comment]
@nlordell this PR solves #1479, right?

**Comment by nlordell** [comment]
It does! Sorry, forgot to link the issue with the PR.

**Pull request merged**
