### PR TITLE
Naive Benchmark for Balancer Sync

### PR DESCRIPTION
**Pull request by bh2smith**
This simple data analysis was collected from the code currently in #696 (event receiving from WeightedPoolFactory with pool info fetching processed sequentially). Note that the performance is not entirely self contained as this was merely a regular run of the orderbook API which is simultaneously responsible for other tasks. To run this exact same simulation again, checkout this branch and run

```sh
cargo run --bin orderbook -- --node-url YOUR-NODE-URL --log-filter shared=info
```

After performing some naive benchmarks, I see no reason to believe that our data fetching is or will ever be a bottle neck even when it is not batched or parallelized. Of course we will eventually have to account for the fact that a cold start will become impractical. In fact, from what we see here (of course this is only data from a product which is not yet live), there would be no improvement gained from batched our requests. Only when several pools are deployed within the same 100 (25 minutes w. 15 second block times) blocks can we expect to see any marginal performance gain from batching requests.

I have found from a single simulation contained in the data logs below that fetching token data for 2 pools and syncing events for about 500 blocks takes < 0.4 seconds (including all other processes that the orderbook API is running in parallel). Only when several pools are deployed within the same 100 blocks (25 minutes w. 15 second block times) can we expect to see any marginal performance gain from batching requests. 

Say, for example that 100 pools are deployed in 25 minutes... then it is expected to take 20 seconds to process and store these events (but of course this would happen without notice at different times during that 25 minute interval).

## Summary of finding from logs:

Spans over:
    1.5 months (April 21 to June 9) - 316_781 blocks

Total time to sync all pools: 8 minutes.

## Points of interest:
- There is only 2 occurrences of > 1 pool created over a period of 1000 block (and these are the real time gaps).
- The real time gap here is not with the pool data fetching, but merely with event sync
      - Between 11 and 12 (128_443 blocks) we have a time gap of 2 minutes and no pools created
      - Between 1 and 3: total time gap of 0.4 seconds to check 500 blocks and fetch the pool info for 2 new pools.

## Comparison with Uniswap V2:

- There are 41_928 pools total. (dune query: `select count(*) from uniswap_v2."Factory_evt_PairCreated"`)
- Total processing time in terms of data fetching (plus 500 block sync) 41_928 * 0.2 (seconds) = 2.3 hours
- For a cold start, this is not ideal!
- However, we can easily handle 5000 pools in 16 minutes.
By this point, I would imagine that we can read/write to an from file to to avoid such issues.

Of course, when comparing with UniswapV2, this looks terrible (especially for a cold start). However, by the time BalancerV2 reaches this magnitude, it should be fairly straightforward to feed a backup of this data into the program at runtime.

## File Size: 
The current amount of data when stored as JSON (without white space or line breaks) is 18kb (2kb compressed). For 20 pools, this makes an average of 1kb per pool. The file store size is then linear with the number of pools. So even when/if balancer reaches the magnitude of uniswapV2 this file should not exceed 42 mb (or 4.2 mb compressed). See file [BalancerPools.txt](https://github.com/gnosis/gp-v2-services/files/6634167/BalancerPools.txt) and compressed [BalancerPools.zip](https://github.com/gnosis/gp-v2-services/files/6634178/BalancerPools.zip)

### Possible next steps to improve evaluation

1. In this PR, vendor the contracts for UniswapV2Factory, and substitute it out for the weighted pool contract in our event storing. 
2. Listen for the `PairCreated` events and then make 3 EVM reads to the pool contract at the address emitted from the event.
3. Time the entire time it takes to sync all 41K pools.

### Raw Data From Naive Benchmark
```
2021-06-10T19:29:39.822Z Last event block 12285749 - Balancer Pool State: 1  pools in store
2021-06-10T19:29:40.201Z Last event block 12286276 - Balancer Pool State: 3  pools in store
2021-06-10T19:29:57.191Z Last event block 12297008 - Balancer Pool State: 4  pools in store
2021-06-10T19:30:00.055Z Last event block 12299382 - Balancer Pool State: 5  pools in store
2021-06-10T19:30:05.540Z Last event block 12303593 - Balancer Pool State: 6  pools in store
2021-06-10T19:30:06.723Z Last event block 12304403 - Balancer Pool State: 7  pools in store
2021-06-10T19:30:23.915Z Last event block 12318074 - Balancer Pool State: 8  pools in store
2021-06-10T19:30:49.069Z Last event block 12331542 - Balancer Pool State: 9  pools in store
2021-06-10T19:30:54.249Z Last event block 12331765 - Balancer Pool State: 10 pools in store
2021-06-10T19:32:16.895Z Last event block 12376911 - Balancer Pool State: 11 pools in store
2021-06-10T19:34:51.197Z Last event block 12505354 - Balancer Pool State: 12 pools in store
2021-06-10T19:34:54.090Z Last event block 12509636 - Balancer Pool State: 13 pools in store
2021-06-10T19:36:11.955Z Last event block 12563369 - Balancer Pool State: 14 pools in store
2021-06-10T19:36:27.052Z Last event block 12567967 - Balancer Pool State: 15 pools in store
2021-06-10T19:37:14.006Z Last event block 12595481 - Balancer Pool State: 16 pools in store
2021-06-10T19:37:15.167Z Last event block 12595681 - Balancer Pool State: 17 pools in store
2021-06-10T19:37:25.202Z Last event block 12602530 - Balancer Pool State: 20 pools in store
```

### CODE REVIEW

**Comment by nlordell** [comment]
> ```
> 2021-06-10T19:29:39.822Z Last event block 12285749 - Balancer Pool State: 1  pools in store
> ...
> 2021-06-10T19:37:25.202Z Last event block 12602530 - Balancer Pool State: 20 pools in store
> ```

So it takes around 8 minutes to sync?

**Comment by bh2smith** [comment]
> Also, how long does it take to sync if there are no eth_calls?

I can run this and check but I can already guess it will not take any less time (since the eth_calls do not appear to be what is slow). will get back to you on this.

**Comment by nlordell** [comment]
Ok, so that's a 7% increase in time. I also would guess that the additional time spent on `eth_call` will scale with the number of Balancer pools (while the time on `eth_getLogs` scales with the number of blocks).

I would also guess that as time goes on, the growth of total pools created will accelerate, and therefore take a larger and larger share of the total execution time. To me, this suggests that the additional `eth_call` overhead can't be ignored.

> could it be the time of day?

Yes, there is a **huge** variance in node request times.

**Comment by fleupold** [comment]
I think in this benchmark we are still fetching all events from the full node instead of filtering only on the one that we are processing. Would you mind running this test again with the filter? I'd assume this to have an impact on the amount of data that needs to be sent over the wire via json and would thus also impact of relative overhead of the unbatched eth_call.

**Comment by bh2smith** [comment]
> I think in this benchmark we are still fetching all events from the full node instead of filtering only

This is on the event listener for the `WeightedPoolFactory` contract which only emits a single event (`PoolCreated`). I don't see how there is any kind of filtering that can be achieved by this.

**Comment by bh2smith** [comment]
Update with Two Token listener included. Even more evidence to suggest that the web3 calls are not performance hindering (look at the jumps around the 10 pool mark

```
2021-06-12T06:28:35.471Z  Last updated block 12363041 - loaded 1 pools
2021-06-12T06:28:35.965Z  Last updated block 12363659 - loaded 2 pools
2021-06-12T06:28:41.394Z  Last updated block 12367800 - loaded 3 pools
2021-06-12T06:28:42.841Z  Last updated block 12368069 - loaded 5 pools
2021-06-12T06:28:44.673Z  Last updated block 12369384 - loaded 10 pools
2021-06-12T06:28:46.615Z  Last updated block 12369886 - loaded 23 pools
2021-06-12T06:28:47.839Z  Last updated block 12370108 - loaded 32 pools
2021-06-12T06:29:04.995Z  Last updated block 12377374 - loaded 33 pools
2021-06-12T06:30:35.360Z  Last updated block 12437421 - loaded 34 pools
2021-06-12T06:30:53.637Z  Last updated block 12445005 - loaded 35 pools
2021-06-12T06:31:17.189Z  Last updated block 12454935 - loaded 36 pools
2021-06-12T06:32:19.453Z  Last updated block 12504909 - loaded 37 pools
2021-06-12T06:32:24.135Z  Last updated block 12510588 - loaded 39 pools
2021-06-12T06:33:08.168Z  Last updated block 12549331 - loaded 41 pools
2021-06-12T06:34:22.299Z  Last updated block 12616747 - loaded 44 pools
2021-06-12T06:34:23.973Z  Last updated block 12617821 - loaded 47 pools
... Weird that it started over again...
2021-06-12T06:34:32.234Z  Last updated block 12285749 - loaded 1 pools
2021-06-12T06:34:32.702Z  Last updated block 12286276 - loaded 3 pools
2021-06-12T06:34:40.717Z  Last updated block 12297008 - loaded 4 pools
2021-06-12T06:34:41.995Z  Last updated block 12299382 - loaded 5 pools
2021-06-12T06:34:45.447Z  Last updated block 12303593 - loaded 6 pools
2021-06-12T06:34:46.129Z  Last updated block 12304403 - loaded 7 pools
2021-06-12T06:34:59.799Z  Last updated block 12318074 - loaded 8 pools
2021-06-12T06:35:08.796Z  Last updated block 12331542 - loaded 9 pools
2021-06-12T06:35:09.209Z  Last updated block 12331765 - loaded 10 pools
```

However, something weird happened... it started over again once it had all the events!

**Comment by bh2smith** [comment]
After most recent changes from #717 we see that everything is functioning as expected:

```
2021-06-15T09:10:02.058Z - Last updated block 12363041 - loaded 1 balancer pools
2021-06-15T09:10:02.167Z - Last updated block 12363659 - loaded 2 balancer pools
2021-06-15T09:10:10.763Z - Last updated block 12367800 - loaded 3 balancer pools
2021-06-15T09:10:12.631Z - Last updated block 12368069 - loaded 5 balancer pools
2021-06-15T09:10:16.014Z - Last updated block 12369384 - loaded 10 balancer pools
2021-06-15T09:10:24.719Z - Last updated block 12369886 - loaded 23 balancer pools
2021-06-15T09:10:27.094Z - Last updated block 12370108 - loaded 32 balancer pools
2021-06-15T09:10:41.908Z - Last updated block 12377374 - loaded 33 balancer pools
2021-06-15T09:13:57.386Z - Last updated block 12437421 - loaded 34 balancer pools
2021-06-15T09:14:13.025Z - Last updated block 12445005 - loaded 35 balancer pools
2021-06-15T09:14:26.873Z - Last updated block 12454935 - loaded 36 balancer pools
2021-06-15T09:16:01.879Z - Last updated block 12504909 - loaded 37 balancer pools
2021-06-15T09:16:14.186Z - Last updated block 12510588 - loaded 39 balancer pools
2021-06-15T09:18:24.264Z - Last updated block 12549331 - loaded 41 balancer pools
2021-06-15T09:20:38.111Z - Last updated block 12616747 - loaded 44 balancer pools
2021-06-15T09:20:49.938Z - Last updated block 12617821 - loaded 47 balancer pools
2021-06-15T09:21:11.592Z - Last updated block 12622961 - loaded 48 balancer pools
2021-06-15T09:22:12.725Z - Registry has 48 pools
2021-06-15T09:22:44.132Z - Last updated block 12285749 - loaded 1 balancer pools
2021-06-15T09:22:45.312Z - Last updated block 12286276 - loaded 3 balancer pools
2021-06-15T09:23:45.829Z - Last updated block 12297008 - loaded 4 balancer pools
2021-06-15T09:23:50.415Z - Last updated block 12299382 - loaded 5 balancer pools
2021-06-15T09:23:56.097Z - Last updated block 12303593 - loaded 6 balancer pools
2021-06-15T09:23:56.883Z - Last updated block 12304403 - loaded 7 balancer pools
2021-06-15T09:24:11.973Z - Last updated block 12318074 - loaded 8 balancer pools
2021-06-15T09:24:25.634Z - Last updated block 12331542 - loaded 9 balancer pools
2021-06-15T09:24:26.386Z - Last updated block 12331765 - loaded 10 balancer pools
2021-06-15T09:25:26.353Z - Last updated block 12376911 - loaded 11 balancer pools
2021-06-15T09:31:42.949Z - Last updated block 12505354 - loaded 12 balancer pools
2021-06-15T09:32:03.638Z - Last updated block 12509636 - loaded 13 balancer pools
2021-06-15T09:34:10.029Z - Last updated block 12563369 - loaded 14 balancer pools
2021-06-15T09:34:16.374Z - Last updated block 12567967 - loaded 15 balancer pools
2021-06-15T09:34:40.428Z - Last updated block 12595481 - loaded 16 balancer pools
2021-06-15T09:34:40.809Z - Last updated block 12595681 - loaded 17 balancer pools
2021-06-15T09:34:47.599Z - Last updated block 12602530 - loaded 20 balancer pools
2021-06-15T09:35:25.974Z - Last updated block 12622158 - loaded 21 balancer pools
2021-06-15T09:35:27.139Z - Last updated block 12624192 - loaded 22 balancer pools
2021-06-15T09:35:52.314Z - Last updated block 12635141 - loaded 23 balancer pools
2021-06-15T09:35:59.798Z - Registry has 71 pools
```

**Comment by bh2smith** [comment]
Closing because too far outdated.

**Pull request closed without merging**
