### PR TITLE
Balancer Coverage Part 1

### PR DESCRIPTION
**Pull request by bh2smith**
Something particularly interesting here is that two ?s in weighted_math.rs were changed to expect including a proof that the error can never occur.

### CODE REVIEW

**Review by vkgnosis — APPROVED** [review]
All the coverage stuff is good. I'm less sure about the expect because:
-  there might be an error in the proof (even though i did not find one)
- it is less error prone to always do checked operations like when we refactor other code so maybe the proof no longer holds

On the other hand I do like unwrap for cases that should never happen.

**Review by nlordell — APPROVED** [review]

**Comment by nlordell** [comment]
I also prefer `unwrap` for cases that shouldn't happen. Nice proof :smile:

**Comment by bh2smith** [comment]
> I also prefer `unwrap` for cases that shouldn't happen. Nice proof 😄

So, are you guys suggesting I change the expect to unwrap (or are you using them as synonyms)?

**Comment by nlordell** [comment]
> are you guys suggesting I change the expect to unwrap (or are you using them as synonyms)?

Synonyms. `expect` is `unwrap` with a message. I was agreeing that we should panic if something that should never happen does happen (instead of propagating a result).

**Comment by vkgnosis** [comment]
Something with the auto update to main probably went wrong so the lock file isn't up to date. Check out your branch and do a `cargo check`. After that you should see that something in the lock file has changed. Commit the new lock file and it should work.

**Comment by nlordell** [comment]
It looks like #1134 bumped `gas-estimate` crate to the tag `v0.3.3` in the lock file, and is causing issues.

**Comment by vkgnosis** [comment]
Hmm. Surprised CI didn't catch that. Will make a fix.

**Pull request merged**
