### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by vkgnosis**
Combination of the dependabot PRs to save CI time.

### Test Plan
CI

### CODE REVIEW

**Comment by vkgnosis** [comment]
Turns out I can't merge without review so I guess we'll wait.

**Review by bh2smith — APPROVED** [review]
This is fine, but the diff shows only one crate being updated.

**Comment by vkgnosis** [comment]
The other updates are in Cargo.lock which Github hides by default.

**Comment by bh2smith** [comment]
Yea, but shouldn't the toml files show the updated dependencies as well? Or after they blanketed by a > or Something?

**Comment by vkgnosis** [comment]
If you write 1.3 in the toml file then Cargo takes that to mean anything that is compatible with so it could be 1.3, 1.4, etc. We usually don't specify the patch version number so it also allows 1.3.1, 1.3.2 etc.

**Pull request merged**
