### PR TITLE
[Paraswap] Parse PriceQuotes that contain error+route as error

### PR DESCRIPTION
**Pull request by fleupold**
We are sometimes getting responses from the paraswap Price Query that contain both an error and a price route (like [this one](https://logs.gnosisdev.com/app/kibana#/discover/doc/de1f5360-a9ae-11ea-acbb-9d2e3cb124ca/logstash-2021.08.27?id=oXi8h3sBlg1NXsCMnHbu)). We currently classify those as success and are trying to convert them into a settlement tx.

This request always fails with an error that happens to be "retryable" (PriceChanged). However, since the price impact is too high our subsequent retries also run into the same issue.

This PR makes it so that we classify mixed responses as error. For now, we will still retry that error however (I will change TooMuchSlippage to not be retryable in a next PR)

### Test Plan
Added a unit test for mixed deserialization.

### CODE REVIEW

**Review by nlordell — APPROVED** [review]

**Review by bh2smith — APPROVED** [review]
I love that reversing the order of the enum changes the parsed result.

**Comment by nlordell** [comment]
> I love that reversing the order of the annum changes the parsed result.

Maybe this may be a reason to consider making the `Deserialize` implementation more explicit?

**Comment by bh2smith** [comment]
> > I love that reversing the order of the enum changes the parsed result.
> 
> Maybe this is a reason to consider making the `Deserialize` implementation more explicit?

Should we create an issue for this?

**Review by vkgnosis — APPROVED** [review]

**Comment by vkgnosis** [comment]
Once you understand what is happening it makes sense that the order matters because serde in general will ignore unknown fields and this is an untagged enum. I would just add a comment to the enum explaining that the order is important but I don't think we need to manually implement Deserialize.

**Pull request merged**
